### ISSUE TITLE
Add State PDF export, Copy Update

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-export#19]
Generate a PDF export for each state.

**Comment by alegzandach** [comment]
also, 

- About the Data page: change 2nd paragraph copy to "The SEDA data are based on the standardized accountability tests in math and Reading Language Arts (RLA) administered by each state to all public-school students in grades 3–8 in each school year from 2008–09 through 2017–18. In these years, 3rd- through 8th-graders in U.S. public schools took roughly 350 million standardized math and RLA tests."

- And then in the PDF itself on the "Trend in Test Scores" page/section, can we change the years in the 1st paragraph 2nd sentence to "2009-2018"
