### ISSUE TITLE
Label X/Y variable names in overlay

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-export#4]
Instead of X / Y in overlay, we should have the variables names 

e.g. 
Socioeconomic Status: 0.37
Average Test Scores: -0.35

![image](https://user-images.githubusercontent.com/21034/64998315-e0d60480-d8a0-11e9-8ec2-15bf9bcad347.png)

**Comment by amygroshek** [comment]
Pushed a fixup for this. Had to alter the label width a bit... @james-minton Feel free to reopen if the labels need touch-ups.
